### ISSUE TITLE
doesn't work in latest versions of Minecraft

### ISSUE THREAD

**Issue by axtonprice** [MCBans/MCBans#120]
Not working as of 1.19.2, 2023.
Receiving `java.net.ConnectException: Connection refused` errors

**Comment by axtonprice** [comment]
```[03:18:33 INFO]: [MCBans] Connecting to the API server.
[03:18:34 INFO]: [MCBans] API Server found: api.mcbans.com :: response time: 477
[03:18:34 INFO]: [MCBans] Fastest server selected: api.mcbans.com :: response time: 477
[03:18:42 WARN]: java.net.ConnectException: Connection refused
[03:18:42 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[03:18:42 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
[03:18:42 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
[03:18:42 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[03:18:42 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[03:18:42 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[03:18:42 WARN]:        at java.base/java.net.Socket.connect(Socket.java:583)
[03:18:42 WARN]:        at java.base/java.net.Socket.<init>(Socket.java:507)
[03:18:42 WARN]:        at java.base/java.net.Socket.<init>(Socket.java:287)
[03:18:42 WARN]:        at MCBans-5.1.0.jar//com.mcbans.client.Client.<init>(Client.java:49)
[03:18:42 WARN]:        at MCBans-5.1.0.jar//com.mcbans.client.ConnectionPool.getConnection(ConnectionPool.java:27)
[03:18:42 WARN]:        at MCBans-5.1.0.jar//com.mcbans.plugin.callBacks.BanSync.startSync(BanSync.java:52)
[03:18:42 WARN]:        at MCBans-5.1.0.jar//com.mcbans.plugin.callBacks.BanSync$7.run(BanSync.java:294)
[03:18:42 WARN]:        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[03:18:42 WARN]:        at java.base/java.util.TimerThread.run(Timer.java:516)```
