### ISSUE TITLE
[ERROR] PlayerJoinEvent v4.3.5

### ISSUE THREAD

**Issue by Aggroblut** [MCBans/MCBans#84]
Hey,

I'm running latest version of McBans and latest Version of  Spigot (atm) and every player login get this error:
```
[18:32:29] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to MCBans v4.3.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:263) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:148) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [craftbukkit.jar:git-Spigot-081dfa5-7658819]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_65]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.mcbans.firestar.mcbans.bukkitListeners.PlayerListener.onPlayerJoin(PlayerListener.java:175) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[craftbukkit.jar:git-Spigot-081dfa5-7658819]
	... 14 more
```

Please help me!

**Comment by JavaPortals** [comment]
Hey,

This was fixed in a recent API Backend update.
