### ISSUE TITLE
Exception in thread "Thread-18" - every start

### ISSUE THREAD

**Issue by Aggroblut** [MCBans/MCBans#88]
```
[07:00:49] [Thread-18/WARN]: Exception in thread "Thread-18" 
[07:00:49] [Thread-18/WARN]: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
[07:00:49] [Thread-18/WARN]: 	at com.mcbans.firestar.mcbans.callBacks.BanSync.startSync(BanSync.java:69)
[07:00:49] [Thread-18/WARN]: 	at com.mcbans.firestar.mcbans.callBacks.BanSync.run(BanSync.java:41)
[07:00:49] [Thread-18/WARN]: 	at java.lang.Thread.run(Unknown Source)
[07:00:49] [Thread-18/WARN]: Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
[07:00:49] [Thread-18/WARN]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[07:00:49] [Thread-18/WARN]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[07:00:49] [Thread-18/WARN]: 	at java.security.AccessController.doPrivileged(Native Method)
[07:00:49] [Thread-18/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[07:00:49] [Thread-18/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[07:00:49] [Thread-18/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[07:00:49] [Thread-18/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[07:00:49] [Thread-18/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[07:00:49] [Thread-18/WARN]: 	... 3 more
```

His happens every start. Would an Spigot update help? I dont use bungee. Only Spigot from December and mcbans latest.

**Comment by JavaPortals** [comment]
Hey,

This issue was fixed a few days ago. Unfortunately a release with the fix haven't been made.
You can however download the source of the plugin from github and compile it yourself.

- Roe
