### ISSUE TITLE
 Exception in thread "Thread-65" - Unban UUID

### ISSUE THREAD

**Issue by Aggroblut** [MCBans/MCBans#89]
```
[13:03:02] [Server thread/INFO]: Schneidertm issued server command: /unban fa233ec9-8825-440b-875d-bdf5b565266a
[13:03:02] [Server thread/INFO]: target: 
[13:03:02] [Server thread/INFO]: targetUUID: fa233ec9-8825-440b-875d-bdf5b565266a
[13:03:02] [Thread-65/WARN]: Exception in thread "Thread-65" 
[13:03:02] [Thread-65/WARN]: java.lang.IllegalArgumentException: Name cannot be blank
[13:03:02] [Thread-65/WARN]:    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
[13:03:02] [Thread-65/WARN]:    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.getOfflinePlayer(CraftServer.java:1281)
[13:03:02] [Thread-65/WARN]:    at com.mcbans.firestar.mcbans.request.Ban.bukkitBan(Ban.java:431)
[13:03:02] [Thread-65/WARN]:    at com.mcbans.firestar.mcbans.request.Ban.unBan(Ban.java:165)
[13:03:02] [Thread-65/WARN]:    at com.mcbans.firestar.mcbans.request.Ban.run(Ban.java:146)
[13:03:02] [Thread-65/WARN]:    at java.lang.Thread.run(Unknown Source)
```

**Comment by Corpdraco** [comment]
Fixed.
